version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: erp_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: erp_web
    env_file:
      - ../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./app:/app
      - ./secrets/gcp-service-account.json:/secrets/gcp-service-account.json:ro
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["/bin/bash", "/app/entrypoint.sh"]

volumes:
  pgdata:
