# Generated by Django 5.0.6 on 2025-09-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_companymembership_company_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bucket_name',
            field=models.CharField(default='default-bucket', max_length=255),
            preserve_default=False,
        ),
    ]
