# Generated by Django 5.0.6 on 2025-09-19 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_bucket_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('bucket_key', models.CharField(max_length=255, unique=True)),
                ('validation_steps', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='documents.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_document_uploads', to=settings.AUTH_USER_MODEL)),
                ('entity_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='documents.entityreference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
